#include "deet_func.h"
#include "commands.h"

COMMANDS commands[] = {
        {CMD_HELP, "help",
                "Print this help message",
        0, 0},
        {CMD_QUIT, "quit",
                "Quit the program",
        -1, 0},
        {CMD_SHOW, "show",
                "Show process info",
        -1, 1},
        {CMD_RUN, "run",
                "Start a process",
        1, -1},
        {CMD_STOP, "stop",
                "Stop a running process",
        1, 1},
        {CMD_CONT, "cont",
                "Continue a stopped process",
        1, 1},
        {CMD_RELEASE, "release",
                "Stop tracing a process, allowing it to continue normally",
        1, 1},
        {CMD_WAIT, "wait",
                "Wait for a process to enter a specified state",
        1, 2},
        {CMD_KILL, "kill",
                "Forcibly terminate a process",
        1, 1},
        {CMD_PEEK, "peek",
                "Read from the address space of a traced process",
        2, 3},
        {CMD_POKE, "poke",
                "Write to the address space of a traced process",
        3, 3},
        {CMD_BT, "bt",
                "Show a stack trace for a traced process",
        1, 1}
};